{
    "52:20:49:hub": {
        "x": 52,
        "y": 20,
        "z": 49,
        "level": "hub",
        "price": 300,
        "item": 169,
        "itemName": "Sea Lantern",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "52:22:49:hub": {
        "x": 52,
        "y": 22,
        "z": 49,
        "level": "hub",
        "price": 600,
        "item": 169,
        "itemName": "Sea Lantern",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "53:20:50:hub": {
        "x": 53,
        "y": 20,
        "z": 50,
        "level": "hub",
        "price": 500,
        "item": 208,
        "itemName": "End Rod",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "53:22:50:hub": {
        "x": 53,
        "y": 22,
        "z": 50,
        "level": "hub",
        "price": 1000,
        "item": 208,
        "itemName": "End Rod",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "54:20:51:hub": {
        "x": 54,
        "y": 20,
        "z": 51,
        "level": "hub",
        "price": 300,
        "item": 47,
        "itemName": "Bookshelf",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "54:22:51:hub": {
        "x": 54,
        "y": 22,
        "z": 51,
        "level": "hub",
        "price": 600,
        "item": 47,
        "itemName": "Bookshelf",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "55:20:52:hub": {
        "x": 55,
        "y": 20,
        "z": 52,
        "level": "hub",
        "price": 1000,
        "item": 389,
        "itemName": "Item Frame",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "55:22:52:hub": {
        "x": 55,
        "y": 22,
        "z": 52,
        "level": "hub",
        "price": 2000,
        "item": 389,
        "itemName": "Item Frame",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "56:20:53:hub": {
        "x": 56,
        "y": 20,
        "z": 53,
        "level": "hub",
        "price": 1000,
        "item": 80,
        "itemName": "Snow Block",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "56:22:53:hub": {
        "x": 56,
        "y": 22,
        "z": 53,
        "level": "hub",
        "price": 2000,
        "item": 80,
        "itemName": "Snow Block",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "57:20:54:hub": {
        "x": 57,
        "y": 20,
        "z": 54,
        "level": "hub",
        "price": 1000,
        "item": 140,
        "itemName": "Flower Pot",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "57:22:54:hub": {
        "x": 57,
        "y": 22,
        "z": 54,
        "level": "hub",
        "price": 2000,
        "item": 140,
        "itemName": "Flower Pot",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "60:20:57:hub": {
        "x": 60,
        "y": 20,
        "z": 57,
        "level": "hub",
        "price": 100,
        "item": 65,
        "itemName": "Ladder",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "60:22:57:hub": {
        "x": 60,
        "y": 22,
        "z": 57,
        "level": "hub",
        "price": 200,
        "item": 65,
        "itemName": "Ladder",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "62:20:59:hub": {
        "x": 62,
        "y": 20,
        "z": 59,
        "level": "hub",
        "price": 200,
        "item": 106,
        "itemName": "Vines",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "62:22:59:hub": {
        "x": 62,
        "y": 22,
        "z": 59,
        "level": "hub",
        "price": 400,
        "item": 106,
        "itemName": "Vines",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "64:20:61:hub": {
        "x": 64,
        "y": 20,
        "z": 61,
        "level": "hub",
        "price": 5000,
        "item": 130,
        "itemName": "Ender Chest",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "64:22:61:hub": {
        "x": 64,
        "y": 22,
        "z": 61,
        "level": "hub",
        "price": 10000,
        "item": 130,
        "itemName": "Ender Chest",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "66:20:63:hub": {
        "x": 66,
        "y": 20,
        "z": 63,
        "level": "hub",
        "price": 100,
        "item": 347,
        "itemName": "Clock",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "66:22:63:hub": {
        "x": 66,
        "y": 22,
        "z": 63,
        "level": "hub",
        "price": 200,
        "item": 347,
        "itemName": "Clock",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "68:20:65:hub": {
        "x": 68,
        "y": 20,
        "z": 65,
        "level": "hub",
        "price": 100,
        "item": 345,
        "itemName": "Compass",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "68:22:65:hub": {
        "x": 68,
        "y": 22,
        "z": 65,
        "level": "hub",
        "price": 200,
        "item": 345,
        "itemName": "Compass",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "70:20:67:hub": {
        "x": 70,
        "y": 20,
        "z": 67,
        "level": "hub",
        "price": 100,
        "item": 6,
        "itemName": "Oak Sapling",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "70:22:67:hub": {
        "x": 70,
        "y": 22,
        "z": 67,
        "level": "hub",
        "price": 200,
        "item": 6,
        "itemName": "Oak Sapling",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "71:20:68:hub": {
        "x": 71,
        "y": 20,
        "z": 68,
        "level": "hub",
        "price": 100,
        "item": 6,
        "itemName": "Spruce Sapling",
        "meta": 1,
        "amount": 1,
        "vip": true
    },
    "71:22:68:hub": {
        "x": 71,
        "y": 22,
        "z": 68,
        "level": "hub",
        "price": 200,
        "item": 6,
        "itemName": "Spruce Sapling",
        "meta": 1,
        "amount": 1,
        "vip": false
    },
    "73:20:70:hub": {
        "x": 73,
        "y": 20,
        "z": 70,
        "level": "hub",
        "price": 100,
        "item": 6,
        "itemName": "Birch Sapling",
        "meta": 2,
        "amount": 1,
        "vip": true
    },
    "73:22:70:hub": {
        "x": 73,
        "y": 22,
        "z": 70,
        "level": "hub",
        "price": 200,
        "item": 6,
        "itemName": "Birch Sapling",
        "meta": 2,
        "amount": 1,
        "vip": false
    },
    "74:20:71:hub": {
        "x": 74,
        "y": 20,
        "z": 71,
        "level": "hub",
        "price": 100,
        "item": 6,
        "itemName": "Jungle Sapling",
        "meta": 3,
        "amount": 1,
        "vip": true
    },
    "74:22:71:hub": {
        "x": 74,
        "y": 22,
        "z": 71,
        "level": "hub",
        "price": 200,
        "item": 6,
        "itemName": "Jungle Sapling",
        "meta": 3,
        "amount": 1,
        "vip": false
    },
    "76:20:73:hub": {
        "x": 76,
        "y": 20,
        "z": 73,
        "level": "hub",
        "price": 100,
        "item": 295,
        "itemName": "Wheat Seeds",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "76:22:73:hub": {
        "x": 76,
        "y": 22,
        "z": 73,
        "level": "hub",
        "price": 200,
        "item": 295,
        "itemName": "Wheat Seeds",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "79:20:76:hub": {
        "x": 79,
        "y": 20,
        "z": 76,
        "level": "hub",
        "price": 1000,
        "item": 372,
        "itemName": "Nether Wart",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "79:22:76:hub": {
        "x": 79,
        "y": 22,
        "z": 76,
        "level": "hub",
        "price": 2000,
        "item": 372,
        "itemName": "Nether Wart",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "81:20:78:hub": {
        "x": 81,
        "y": 20,
        "z": 78,
        "level": "hub",
        "price": 1000,
        "item": 40,
        "itemName": "Red Mushroom",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "81:22:78:hub": {
        "x": 81,
        "y": 22,
        "z": 78,
        "level": "hub",
        "price": 2000,
        "item": 40,
        "itemName": "Red Mushroom",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "82:20:79:hub": {
        "x": 82,
        "y": 20,
        "z": 79,
        "level": "hub",
        "price": 1000,
        "item": 39,
        "itemName": "Brown Mushroom",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "82:22:79:hub": {
        "x": 82,
        "y": 22,
        "z": 79,
        "level": "hub",
        "price": 2000,
        "item": 39,
        "itemName": "Brown Mushroom",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "80:20:81:hub": {
        "x": 80,
        "y": 20,
        "z": 81,
        "level": "hub",
        "price": 1000,
        "item": 81,
        "itemName": "Cactus",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "80:22:81:hub": {
        "x": 80,
        "y": 22,
        "z": 81,
        "level": "hub",
        "price": 2000,
        "item": 81,
        "itemName": "Cactus",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "77:20:84:hub": {
        "x": 77,
        "y": 20,
        "z": 84,
        "level": "hub",
        "price": 1000,
        "item": 338,
        "itemName": "Sugarcane",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "77:22:84:hub": {
        "x": 77,
        "y": 22,
        "z": 84,
        "level": "hub",
        "price": 2000,
        "item": 338,
        "itemName": "Sugarcane",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "75:20:86:hub": {
        "x": 75,
        "y": 20,
        "z": 86,
        "level": "hub",
        "price": 1000,
        "item": 392,
        "itemName": "Potato",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "75:22:86:hub": {
        "x": 75,
        "y": 22,
        "z": 86,
        "level": "hub",
        "price": 2000,
        "item": 392,
        "itemName": "Potato",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "74:20:85:hub": {
        "x": 74,
        "y": 20,
        "z": 85,
        "level": "hub",
        "price": 1000,
        "item": 391,
        "itemName": "Carrot",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "74:22:85:hub": {
        "x": 74,
        "y": 22,
        "z": 85,
        "level": "hub",
        "price": 2000,
        "item": 391,
        "itemName": "Carrot",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "72:20:83:hub": {
        "x": 72,
        "y": 20,
        "z": 83,
        "level": "hub",
        "price": 100,
        "item": 361,
        "itemName": "Pumpkin Seeds",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "72:22:83:hub": {
        "x": 72,
        "y": 22,
        "z": 83,
        "level": "hub",
        "price": 200,
        "item": 361,
        "itemName": "Pumpkin Seeds",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "70:20:81:hub": {
        "x": 70,
        "y": 20,
        "z": 81,
        "level": "hub",
        "price": 1000,
        "item": 362,
        "itemName": "Melon Seeds",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "70:22:81:hub": {
        "x": 70,
        "y": 22,
        "z": 81,
        "level": "hub",
        "price": 2000,
        "item": 362,
        "itemName": "Melon Seeds",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "68:20:79:hub": {
        "x": 68,
        "y": 20,
        "z": 79,
        "level": "hub",
        "price": 250,
        "item": 263,
        "itemName": "Coal",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "68:22:79:hub": {
        "x": 68,
        "y": 22,
        "z": 79,
        "level": "hub",
        "price": 500,
        "item": 263,
        "itemName": "Coal",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "66:20:77:hub": {
        "x": 66,
        "y": 20,
        "z": 77,
        "level": "hub",
        "price": 750,
        "item": 265,
        "itemName": "Iron Ingot",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "66:22:77:hub": {
        "x": 66,
        "y": 22,
        "z": 77,
        "level": "hub",
        "price": 1500,
        "item": 265,
        "itemName": "Iron Ingot",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "63:20:74:hub": {
        "x": 63,
        "y": 20,
        "z": 74,
        "level": "hub",
        "price": 500,
        "item": 331,
        "itemName": "Redstone",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "63:22:74:hub": {
        "x": 63,
        "y": 22,
        "z": 74,
        "level": "hub",
        "price": 1000,
        "item": 331,
        "itemName": "Redstone",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "62:20:73:hub": {
        "x": 62,
        "y": 20,
        "z": 73,
        "level": "hub",
        "price": 2500,
        "item": 266,
        "itemName": "Gold Ingot",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "62:22:73:hub": {
        "x": 62,
        "y": 22,
        "z": 73,
        "level": "hub",
        "price": 5000,
        "item": 266,
        "itemName": "Gold Ingot",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "60:20:71:hub": {
        "x": 60,
        "y": 20,
        "z": 71,
        "level": "hub",
        "price": 5000,
        "item": 388,
        "itemName": "Emerald",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "60:22:71:hub": {
        "x": 60,
        "y": 22,
        "z": 71,
        "level": "hub",
        "price": 10000,
        "item": 388,
        "itemName": "Emerald",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "58:20:69:hub": {
        "x": 58,
        "y": 20,
        "z": 69,
        "level": "hub",
        "price": 5000,
        "item": 264,
        "itemName": "Diamond",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "58:22:69:hub": {
        "x": 58,
        "y": 22,
        "z": 69,
        "level": "hub",
        "price": 10000,
        "item": 264,
        "itemName": "Diamond",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "56:20:67:hub": {
        "x": 56,
        "y": 20,
        "z": 67,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Red Tulip",
        "meta": 4,
        "amount": 1,
        "vip": true
    },
    "56:22:67:hub": {
        "x": 56,
        "y": 22,
        "z": 67,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Red Tulip",
        "meta": 4,
        "amount": 1,
        "vip": false
    },
    "54:20:65:hub": {
        "x": 54,
        "y": 20,
        "z": 65,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Orange Tulip",
        "meta": 5,
        "amount": 1,
        "vip": true
    },
    "54:22:65:hub": {
        "x": 54,
        "y": 22,
        "z": 65,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Orange Tulip",
        "meta": 5,
        "amount": 1,
        "vip": false
    },
    "52:20:63:hub": {
        "x": 52,
        "y": 20,
        "z": 63,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "White Tulip",
        "meta": 6,
        "amount": 1,
        "vip": true
    },
    "52:22:63:hub": {
        "x": 52,
        "y": 22,
        "z": 63,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "White Tulip",
        "meta": 6,
        "amount": 1,
        "vip": false
    },
    "49:20:60:hub": {
        "x": 49,
        "y": 20,
        "z": 60,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Pink Tulip",
        "meta": 7,
        "amount": 1,
        "vip": true
    },
    "49:22:60:hub": {
        "x": 49,
        "y": 22,
        "z": 60,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Pink Tulip",
        "meta": 7,
        "amount": 1,
        "vip": false
    },
    "47:20:58:hub": {
        "x": 47,
        "y": 20,
        "z": 58,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Oxeye Daisy",
        "meta": 8,
        "amount": 1,
        "vip": true
    },
    "47:22:58:hub": {
        "x": 47,
        "y": 22,
        "z": 58,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Oxeye Daisy",
        "meta": 8,
        "amount": 1,
        "vip": false
    },
    "45:20:56:hub": {
        "x": 45,
        "y": 20,
        "z": 56,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Allium",
        "meta": 2,
        "amount": 1,
        "vip": true
    },
    "45:22:56:hub": {
        "x": 45,
        "y": 22,
        "z": 56,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Allium",
        "meta": 2,
        "amount": 1,
        "vip": false
    },
    "44:20:55:hub": {
        "x": 44,
        "y": 20,
        "z": 55,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Blue Orchid",
        "meta": 1,
        "amount": 1,
        "vip": true
    },
    "44:22:55:hub": {
        "x": 44,
        "y": 22,
        "z": 55,
        "level": "hub",
        "price": 40,
        "item": 38,
        "itemName": "Blue Orchid",
        "meta": 1,
        "amount": 1,
        "vip": false
    },
    "62:31:53:hub": {
        "x": 62,
        "y": 31,
        "z": 53,
        "level": "hub",
        "price": 1000,
        "item": 259,
        "itemName": "Flint and Steel",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "62:33:53:hub": {
        "x": 62,
        "y": 33,
        "z": 53,
        "level": "hub",
        "price": 2000,
        "item": 259,
        "itemName": "Flint and Steel",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "64:31:54:hub": {
        "x": 64,
        "y": 31,
        "z": 54,
        "level": "hub",
        "price": 1000,
        "item": 359,
        "itemName": "Shears",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "64:33:54:hub": {
        "x": 64,
        "y": 33,
        "z": 54,
        "level": "hub",
        "price": 2000,
        "item": 359,
        "itemName": "Shears",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "67:31:55:hub": {
        "x": 67,
        "y": 31,
        "z": 55,
        "level": "hub",
        "price": 1000,
        "item": 368,
        "itemName": "Ender Pearl",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "67:33:55:hub": {
        "x": 67,
        "y": 33,
        "z": 55,
        "level": "hub",
        "price": 2000,
        "item": 368,
        "itemName": "Ender Pearl",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "70:31:56:hub": {
        "x": 70,
        "y": 31,
        "z": 56,
        "level": "hub",
        "price": 50000,
        "item": 46,
        "itemName": "TNT",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "70:33:56:hub": {
        "x": 70,
        "y": 33,
        "z": 56,
        "level": "hub",
        "price": 100000,
        "item": 46,
        "itemName": "TNT",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "72:31:58:hub": {
        "x": 72,
        "y": 31,
        "z": 58,
        "level": "hub",
        "price": 100,
        "item": 357,
        "itemName": "Cookie",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "72:33:58:hub": {
        "x": 72,
        "y": 33,
        "z": 58,
        "level": "hub",
        "price": 200,
        "item": 357,
        "itemName": "Cookie",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "73:31:61:hub": {
        "x": 73,
        "y": 31,
        "z": 61,
        "level": "hub",
        "price": 300,
        "item": 366,
        "itemName": "Cooked Chicken",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "73:33:61:hub": {
        "x": 73,
        "y": 33,
        "z": 61,
        "level": "hub",
        "price": 600,
        "item": 366,
        "itemName": "Cooked Chicken",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "74:31:64:hub": {
        "x": 74,
        "y": 31,
        "z": 64,
        "level": "hub",
        "price": 10000,
        "item": 350,
        "itemName": "Cooked Fish",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "74:33:64:hub": {
        "x": 74,
        "y": 33,
        "z": 64,
        "level": "hub",
        "price": 20000,
        "item": 350,
        "itemName": "Cooked Fish",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "75:31:66:hub": {
        "x": 75,
        "y": 31,
        "z": 66,
        "level": "hub",
        "price": 400,
        "item": 400,
        "itemName": "Pumpkin Pie",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "75:33:66:hub": {
        "x": 75,
        "y": 33,
        "z": 66,
        "level": "hub",
        "price": 800,
        "item": 400,
        "itemName": "Pumpkin Pie",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "74:31:68:hub": {
        "x": 74,
        "y": 31,
        "z": 68,
        "level": "hub",
        "price": 400,
        "item": 320,
        "itemName": "Cooked Porkchop",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "74:33:68:hub": {
        "x": 74,
        "y": 33,
        "z": 68,
        "level": "hub",
        "price": 800,
        "item": 320,
        "itemName": "Cooked Porkchop",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "73:31:71:hub": {
        "x": 73,
        "y": 31,
        "z": 71,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Azure Bluet",
        "meta": 3,
        "amount": 1,
        "vip": true
    },
    "73:33:71:hub": {
        "x": 73,
        "y": 33,
        "z": 71,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Azure Bluet",
        "meta": 3,
        "amount": 1,
        "vip": false
    },
    "72:31:74:hub": {
        "x": 72,
        "y": 31,
        "z": 74,
        "level": "hub",
        "price": 10,
        "item": 38,
        "itemName": "Blue Orchid",
        "meta": 1,
        "amount": 1,
        "vip": true
    },
    "72:33:74:hub": {
        "x": 72,
        "y": 33,
        "z": 74,
        "level": "hub",
        "price": 20,
        "item": 38,
        "itemName": "Blue Orchid",
        "meta": 1,
        "amount": 1,
        "vip": false
    },
    "70:31:76:hub": {
        "x": 70,
        "y": 31,
        "z": 76,
        "level": "hub",
        "price": 10,
        "item": 37,
        "itemName": "Dandelion",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "70:33:76:hub": {
        "x": 70,
        "y": 33,
        "z": 76,
        "level": "hub",
        "price": 20,
        "item": 37,
        "itemName": "Dandelion",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "67:31:77:hub": {
        "x": 67,
        "y": 31,
        "z": 77,
        "level": "hub",
        "price": 6400,
        "item": 17,
        "itemName": "Oak Wood",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "67:33:77:hub": {
        "x": 67,
        "y": 33,
        "z": 77,
        "level": "hub",
        "price": 12800,
        "item": 17,
        "itemName": "Oak Wood",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "64:31:78:hub": {
        "x": 64,
        "y": 31,
        "z": 78,
        "level": "hub",
        "price": 6400,
        "item": 17,
        "itemName": "Spruce Wood",
        "meta": 1,
        "amount": 64,
        "vip": true
    },
    "64:33:78:hub": {
        "x": 64,
        "y": 33,
        "z": 78,
        "level": "hub",
        "price": 12800,
        "item": 17,
        "itemName": "Spruce Wood",
        "meta": 1,
        "amount": 64,
        "vip": false
    },
    "62:31:79:hub": {
        "x": 62,
        "y": 31,
        "z": 79,
        "level": "hub",
        "price": 6400,
        "item": 17,
        "itemName": "Birch Wood",
        "meta": 2,
        "amount": 64,
        "vip": true
    },
    "62:33:79:hub": {
        "x": 62,
        "y": 33,
        "z": 79,
        "level": "hub",
        "price": 12800,
        "item": 17,
        "itemName": "Birch Wood",
        "meta": 2,
        "amount": 64,
        "vip": false
    },
    "61:31:79:hub": {
        "x": 61,
        "y": 31,
        "z": 79,
        "level": "hub",
        "price": 6400,
        "item": 17,
        "itemName": "Jungle Wood",
        "meta": 3,
        "amount": 64,
        "vip": true
    },
    "61:33:79:hub": {
        "x": 61,
        "y": 33,
        "z": 79,
        "level": "hub",
        "price": 12800,
        "item": 17,
        "itemName": "Jungle Wood",
        "meta": 3,
        "amount": 64,
        "vip": false
    },
    "57:31:77:hub": {
        "x": 57,
        "y": 31,
        "z": 77,
        "level": "hub",
        "price": 6400,
        "item": 162,
        "itemName": "Acacia Wood",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "57:33:77:hub": {
        "x": 57,
        "y": 33,
        "z": 77,
        "level": "hub",
        "price": 12800,
        "item": 162,
        "itemName": "Acacia Wood",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "54:31:76:hub": {
        "x": 54,
        "y": 31,
        "z": 76,
        "level": "hub",
        "price": 6400,
        "item": 3,
        "itemName": "Dirt",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "54:33:76:hub": {
        "x": 54,
        "y": 33,
        "z": 76,
        "level": "hub",
        "price": 12800,
        "item": 3,
        "itemName": "Dirt",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "52:31:74:hub": {
        "x": 52,
        "y": 31,
        "z": 74,
        "level": "hub",
        "price": 6400,
        "item": 3,
        "itemName": "Coarse Dirt",
        "meta": 1,
        "amount": 64,
        "vip": true
    },
    "52:33:74:hub": {
        "x": 52,
        "y": 33,
        "z": 74,
        "level": "hub",
        "price": 12800,
        "item": 3,
        "itemName": "Coarse Dirt",
        "meta": 1,
        "amount": 64,
        "vip": false
    },
    "51:31:71:hub": {
        "x": 51,
        "y": 31,
        "z": 71,
        "level": "hub",
        "price": 6400,
        "item": 2,
        "itemName": "Grass",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "51:33:71:hub": {
        "x": 51,
        "y": 33,
        "z": 71,
        "level": "hub",
        "price": 12800,
        "item": 2,
        "itemName": "Grass",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "50:31:68:hub": {
        "x": 50,
        "y": 31,
        "z": 68,
        "level": "hub",
        "price": 25600,
        "item": 12,
        "itemName": "Sand",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "50:33:68:hub": {
        "x": 50,
        "y": 33,
        "z": 68,
        "level": "hub",
        "price": 51200,
        "item": 12,
        "itemName": "Sand",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "49:31:66:hub": {
        "x": 49,
        "y": 31,
        "z": 66,
        "level": "hub",
        "price": 25600,
        "item": 12,
        "itemName": "Red Sand",
        "meta": 1,
        "amount": 64,
        "vip": true
    },
    "49:33:66:hub": {
        "x": 49,
        "y": 33,
        "z": 66,
        "level": "hub",
        "price": 51200,
        "item": 12,
        "itemName": "Red Sand",
        "meta": 1,
        "amount": 64,
        "vip": false
    },
    "50:31:64:hub": {
        "x": 50,
        "y": 31,
        "z": 64,
        "level": "hub",
        "price": 1600,
        "item": 82,
        "itemName": "Clay Block",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "50:33:64:hub": {
        "x": 50,
        "y": 33,
        "z": 64,
        "level": "hub",
        "price": 3200,
        "item": 82,
        "itemName": "Clay Block",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "51:31:61:hub": {
        "x": 51,
        "y": 31,
        "z": 61,
        "level": "hub",
        "price": 3200,
        "item": 20,
        "itemName": "Glass",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "51:33:61:hub": {
        "x": 51,
        "y": 33,
        "z": 61,
        "level": "hub",
        "price": 6400,
        "item": 20,
        "itemName": "Glass",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "52:31:58:hub": {
        "x": 52,
        "y": 31,
        "z": 58,
        "level": "hub",
        "price": 12800,
        "item": 1,
        "itemName": "Stone",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "52:33:58:hub": {
        "x": 52,
        "y": 33,
        "z": 58,
        "level": "hub",
        "price": 25600,
        "item": 1,
        "itemName": "Stone",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "54:31:56:hub": {
        "x": 54,
        "y": 31,
        "z": 56,
        "level": "hub",
        "price": 12800,
        "item": 4,
        "itemName": "Cobblestone",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "54:33:56:hub": {
        "x": 54,
        "y": 33,
        "z": 56,
        "level": "hub",
        "price": 25600,
        "item": 4,
        "itemName": "Cobblestone",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "57:31:55:hub": {
        "x": 57,
        "y": 31,
        "z": 55,
        "level": "hub",
        "price": 25600,
        "item": 98,
        "itemName": "Stone Bricks",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "57:33:55:hub": {
        "x": 57,
        "y": 33,
        "z": 55,
        "level": "hub",
        "price": 51200,
        "item": 98,
        "itemName": "Stone Bricks",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "60:31:54:hub": {
        "x": 60,
        "y": 31,
        "z": 54,
        "level": "hub",
        "price": 19200,
        "item": 45,
        "itemName": "Bricks",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "60:33:54:hub": {
        "x": 60,
        "y": 33,
        "z": 54,
        "level": "hub",
        "price": 38400,
        "item": 45,
        "itemName": "Bricks",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "49:31:67:hub": {
        "x": 49,
        "y": 31,
        "z": 67,
        "level": "hub",
        "price": 16000,
        "item": 87,
        "itemName": "Netherrack",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "49:33:67:hub": {
        "x": 49,
        "y": 33,
        "z": 67,
        "level": "hub",
        "price": 32000,
        "item": 87,
        "itemName": "Netherrack",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "49:31:63:hub": {
        "x": 49,
        "y": 31,
        "z": 63,
        "level": "hub",
        "price": 64000,
        "item": 112,
        "itemName": "Nether Bricks",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "49:33:63:hub": {
        "x": 49,
        "y": 33,
        "z": 63,
        "level": "hub",
        "price": 128000,
        "item": 112,
        "itemName": "Nether Bricks",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "50:31:60:hub": {
        "x": 50,
        "y": 31,
        "z": 60,
        "level": "hub",
        "price": 64000,
        "item": 215,
        "itemName": "Red Nether Bricks",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "50:33:60:hub": {
        "x": 50,
        "y": 33,
        "z": 60,
        "level": "hub",
        "price": 128000,
        "item": 215,
        "itemName": "Red Nether Bricks",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "52:31:57:hub": {
        "x": 52,
        "y": 31,
        "z": 57,
        "level": "hub",
        "price": 16000,
        "item": 155,
        "itemName": "Quartz Block",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "52:33:57:hub": {
        "x": 52,
        "y": 33,
        "z": 57,
        "level": "hub",
        "price": 32000,
        "item": 155,
        "itemName": "Quartz Block",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "53:31:56:hub": {
        "x": 53,
        "y": 31,
        "z": 56,
        "level": "hub",
        "price": 25600,
        "item": 206,
        "itemName": "End Stone Bricks",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "53:33:56:hub": {
        "x": 53,
        "y": 33,
        "z": 56,
        "level": "hub",
        "price": 51200,
        "item": 206,
        "itemName": "End Stone Bricks",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "56:31:56:hub": {
        "x": 56,
        "y": 31,
        "z": 56,
        "level": "hub",
        "price": 25600,
        "item": 168,
        "itemName": "Prismarine Bricks",
        "meta": 2,
        "amount": 64,
        "vip": true
    },
    "56:33:56:hub": {
        "x": 56,
        "y": 33,
        "z": 56,
        "level": "hub",
        "price": 51200,
        "item": 168,
        "itemName": "Prismarine Bricks",
        "meta": 2,
        "amount": 64,
        "vip": false
    },
    "59:31:54:hub": {
        "x": 59,
        "y": 31,
        "z": 54,
        "level": "hub",
        "price": 64000,
        "item": 49,
        "itemName": "Obsidian",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "59:33:54:hub": {
        "x": 59,
        "y": 33,
        "z": 54,
        "level": "hub",
        "price": 128000,
        "item": 49,
        "itemName": "Obsidian",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "63:31:53:hub": {
        "x": 63,
        "y": 31,
        "z": 53,
        "level": "hub",
        "price": 100,
        "item": 58,
        "itemName": "Crafting Table",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "63:33:53:hub": {
        "x": 63,
        "y": 33,
        "z": 53,
        "level": "hub",
        "price": 200,
        "item": 58,
        "itemName": "Crafting Table",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "66:31:54:hub": {
        "x": 66,
        "y": 31,
        "z": 54,
        "level": "hub",
        "price": 100,
        "item": 61,
        "itemName": "Furnace",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "66:33:54:hub": {
        "x": 66,
        "y": 33,
        "z": 54,
        "level": "hub",
        "price": 200,
        "item": 61,
        "itemName": "Furnace",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "69:31:55:hub": {
        "x": 69,
        "y": 31,
        "z": 55,
        "level": "hub",
        "price": 100,
        "item": 145,
        "itemName": "Anvil",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "69:33:55:hub": {
        "x": 69,
        "y": 33,
        "z": 55,
        "level": "hub",
        "price": 200,
        "item": 145,
        "itemName": "Anvil",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "71:31:57:hub": {
        "x": 71,
        "y": 31,
        "z": 57,
        "level": "hub",
        "price": 100,
        "item": 117,
        "itemName": "Brewing Stand",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "71:33:57:hub": {
        "x": 71,
        "y": 33,
        "z": 57,
        "level": "hub",
        "price": 200,
        "item": 117,
        "itemName": "Brewing Stand",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "74:31:60:hub": {
        "x": 74,
        "y": 31,
        "z": 60,
        "level": "hub",
        "price": 100,
        "item": 116,
        "itemName": "Enchanting Table",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "74:33:60:hub": {
        "x": 74,
        "y": 33,
        "z": 60,
        "level": "hub",
        "price": 200,
        "item": 116,
        "itemName": "Enchanting Table",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "75:31:63:hub": {
        "x": 75,
        "y": 31,
        "z": 63,
        "level": "hub",
        "price": 2400,
        "item": 47,
        "itemName": "Bookshelf",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "75:33:63:hub": {
        "x": 75,
        "y": 33,
        "z": 63,
        "level": "hub",
        "price": 4800,
        "item": 47,
        "itemName": "Bookshelf",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "75:33:67:hub": {
        "x": 75,
        "y": 33,
        "z": 67,
        "level": "hub",
        "price": 4800,
        "item": 47,
        "itemName": "Bookshelf",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "75:31:67:hub": {
        "x": 75,
        "y": 31,
        "z": 67,
        "level": "hub",
        "price": 10,
        "item": 50,
        "itemName": "Torch",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "75:31:69:hub": {
        "x": 75,
        "y": 31,
        "z": 69,
        "level": "hub",
        "price": 4000,
        "item": 389,
        "itemName": "Item Frame",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "75:33:69:hub": {
        "x": 75,
        "y": 33,
        "z": 69,
        "level": "hub",
        "price": 8000,
        "item": 389,
        "itemName": "Item Frame",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "74:31:72:hub": {
        "x": 74,
        "y": 31,
        "z": 72,
        "level": "hub",
        "price": 350,
        "item": 123,
        "itemName": "Redstone Lamp",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "74:33:72:hub": {
        "x": 74,
        "y": 33,
        "z": 72,
        "level": "hub",
        "price": 700,
        "item": 123,
        "itemName": "Redstone Lamp",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "71:31:76:hub": {
        "x": 71,
        "y": 31,
        "z": 76,
        "level": "hub",
        "price": 3200000,
        "item": 7,
        "itemName": "Bedrock",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "68:31:78:hub": {
        "x": 68,
        "y": 31,
        "z": 78,
        "level": "hub",
        "price": 100000,
        "item": 154,
        "itemName": "Hopper",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "59:31:79:hub": {
        "x": 59,
        "y": 31,
        "z": 79,
        "level": "hub",
        "price": 6400,
        "item": 80,
        "itemName": "Snow Block",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "59:33:79:hub": {
        "x": 59,
        "y": 33,
        "z": 79,
        "level": "hub",
        "price": 12800,
        "item": 80,
        "itemName": "Snow Block",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "56:31:78:hub": {
        "x": 56,
        "y": 31,
        "z": 78,
        "level": "hub",
        "price": 6400,
        "item": 79,
        "itemName": "Ice",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "56:33:78:hub": {
        "x": 56,
        "y": 33,
        "z": 78,
        "level": "hub",
        "price": 12800,
        "item": 79,
        "itemName": "Ice",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "53:31:77:hub": {
        "x": 53,
        "y": 31,
        "z": 77,
        "level": "hub",
        "price": 6400,
        "item": 81,
        "itemName": "Cactus",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "53:33:77:hub": {
        "x": 53,
        "y": 33,
        "z": 77,
        "level": "hub",
        "price": 12800,
        "item": 81,
        "itemName": "Cactus",
        "meta": 0,
        "amount": 64,
        "vip": false
    },
    "52:31:75:hub": {
        "x": 52,
        "y": 31,
        "z": 75,
        "level": "hub",
        "price": 6400,
        "item": 86,
        "itemName": "Pumpkin",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "52:33:75:hub": {
        "x": 52,
        "y": 33,
        "z": 75,
        "level": "hub",
        "price": 12800,
        "item": 86,
        "itemName": "Pumpkin",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "50:31:70:hub": {
        "x": 50,
        "y": 31,
        "z": 70,
        "level": "hub",
        "price": 12800,
        "item": 138,
        "itemName": "Unknown",
        "meta": 0,
        "amount": 1,
        "vip": true
    },
    "50:33:70:hub": {
        "x": 50,
        "y": 33,
        "z": 70,
        "level": "hub",
        "price": 25600,
        "item": 138,
        "itemName": "Unknown",
        "meta": 0,
        "amount": 1,
        "vip": false
    },
    "50:31:62:hub": {
        "x": 50,
        "y": 31,
        "z": 62,
        "level": "hub",
        "price": 64800,
        "item": 213,
        "itemName": "Magma Block",
        "meta": 0,
        "amount": 64,
        "vip": true
    },
    "50:33:62:hub": {
        "x": 50,
        "y": 33,
        "z": 62,
        "level": "hub",
        "price": 129600,
        "item": 213,
        "itemName": "Magma Block",
        "meta": 0,
        "amount": 64,
        "vip": false
    }
}