name: FactionsPro
author: kenygamer
description: A Plugin For Easily Managing Factions
version: 1.4.2
main: FactionsPro\FactionMain
api: [3.0.0, 4.0.0]
#softdepend: ["PureChat"] Fix for circular dependency
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
  f.command.addstrto.subtract:
    description: "Specific permission to subtract STR from a faction"
    default: op